pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'OData-Parser'
  displayName: "Install NPM Dependencies"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
    workingDir: 'OData-Parser'
  displayName: "Test"

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'scripts'
  displayName: "Install 'scripts' NPM Dependencies"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: 'OData-Parser'
  displayName: "Build"

- task: Npm@1
  condition: eq(variables['Build.SourceBranchName'], 'main')
  inputs:
    command: 'custom'
    customCommand: 'run semantic-release'
    workingDir: 'OData-Parser'
  displayName: "Semantic Release"

- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage results"
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "OData-Parser/coverage/cobertura-coverage.xml"
