pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: "Install NPM Dependencies"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
  displayName: "Test"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: "Build"

- script: 'npx semantic-release'
  displayName: 'Semantic Release'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    NPM_TOKEN: $(NPM_TOKEN)

- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage results"
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "coverage/cobertura-coverage.xml"
